### ISSUE TITLE
NoSuchMethod Exception

### ISSUE THREAD

**Issue by Ddantee000** [Starexify/HexxiGearR#1]
Hi there, I've checked for dependencies or anything like that but it doesn't look like there are some, so this issue has been occurring in 1.20.1 with Forge recommended download which is this: https://adfoc.us/serve/sitelinks/?id=271228&url=https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.1-47.3.0/forge-1.20.1-47.3.0-installer.jar

Error loading mods and shows this before post with the main menu:

![image](https://github.com/user-attachments/assets/82344b4f-aa89-4bb8-b393-5c354acc532a)

I didn't add the modlist cuz there are over 500... But in case is needed I can add the list, no problem

**Comment by Starexify** [comment]
Which Forge version do you use?
Edit: Oh I see 47.3.0, then I would recommend using newest version of Forge rather. But I will try fix the issue if not possible to update Forge

**Comment by Ddantee000** [comment]
> Which Forge version do you use? Edit: Oh I see 47.3.0, then I would recommend using newest version of Forge rather. But I will try fix the issue if not possible to update Forge

It's ok, actually I downgraded my forge to this version to check if it was more stable but... I see no.. xd for me I'd use neoforge but you know... mods until forge 1.20.1 and not being updated anymore obliges you stay in the past 🤘🏻 I'll check again with the latest instead the recommended one

**Comment by Starexify** [comment]
Oh I think I know why that happens, I forgot to update the code like I did to Big Swords R on 1.20.1, yeeaa I will release a fix for this as 1.0.1 😅

**Comment by Starexify** [comment]
Fixed in #2
